# Generated by Django 4.2.7 on 2023-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
