# Generated by Django 4.2.7 on 2023-11-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customer_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_spending',
            field=models.IntegerField(default=0),
        ),
    ]
