# Generated by Django 4.2.7 on 2023-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customer_total_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_spending',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
